### ISSUE TITLE
P2-Project_Outline - Overview

### ISSUE THREAD

**Issue by CJBless** [santhoshni/liftoff-assignments#1]
I like your changes to the overview! I'd say the one thing we're missing is what store the shopping cart is for, this can be one of two things.  Are we making this for a specific store as discussed, or are we making this a generic store application that other store owners can use and fill with their own categories/products/information?

**Comment by santhoshni** [comment]
Thank you,  I have added more overview about this project and why I have taken this project and this project is focusing the specific businesses.

**Comment by CJBless** [comment]
Looks good!
