### ISSUE TITLE
P2-Project_Outline - Features

### ISSUE THREAD

**Issue by CJBless** [santhoshni/liftoff-assignments#2]
Let's add all of the features we discussed to this list.
List out each feature on its own line.
Fix typos in second feature (categories) and last feature (product)

For categories, we can be more specific and say the users can search by product type.
Add reordering items as its own feature, the option to save the data of a user's past purchases into a reorder category.
For the products feature description, let's re-word this to say that users can add a certain quantity to their shopping cart, and remove the item from the shopping cart.

**Comment by santhoshni** [comment]
Thank you,  I have added comments and it's explain the basic operations. Not sure is that enough. I'll add further more based on feature implementation. Please check.

**Comment by CJBless** [comment]
I see the updates, let's keep this open for now as a reminder to us to go back and edit this once we've lined up which features you can implement.

**Comment by santhoshni** [comment]
Ok CJ. Thank you.
