### ISSUE TITLE
P3- Project_Planning

### ISSUE THREAD

**Issue by CJBless** [santhoshni/liftoff-assignments#3]
For all your wireframes here: https://github.com/santhoshni/shoppingcart/tree/work/Wireframes

Can you open the files, grab the direct link to them, and list them under the Project Planning assignment in this repository under the Wireframes subheader (in a bulleted unordered list as described)

Also add your Trello board link under the Project Tracker subheader.

and a link to the shopping cart repository under the Project Repo Link subheader

**Comment by santhoshni** [comment]
Created direct link under the project planning assignment section. Created bulleted unorder list. 
Trello link added

shopping cart repo link added either at respective places.

**Comment by CJBless** [comment]
Awesome, and last thing I forgot to add, on Canvas, can you resubmit the repository link in the Project Planning assignment, it should link here instead of your projectl repository: https://github.com/santhoshni/liftoff-assignments/tree/master/P3-Project_Planning

**Comment by santhoshni** [comment]
Thank you CJ. I resubmitted  the repository link in the Project Planning assignment
